### ISSUE TITLE
implement a global error handler 

### ISSUE THREAD

**Issue by sergeybobryk** [sergeybobryk/express-mongoose-jwt-es6-api#2]
Prevent errors like:

```bash
MongoError: E11000 duplicate key error collection: 5a3e1ad9c0c6e35067ef43cf_express-mongoose-jwt-es6-api-database.users index: email_1 dup key: { : "u
ser14@user14.com" }
    at Function.MongoError.create (D:\Projects\express-mongoose-jwt-es6-api\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (D:\Projects\express-mongoose-jwt-es6-api\node_modules\mongodb\lib\utils.js:139:22)
    at D:\Projects\express-mongoose-jwt-es6-api\node_modules\mongodb\lib\collection.js:668:23
    at handleCallback (D:\Projects\express-mongoose-jwt-es6-api\node_modules\mongodb\lib\utils.js:120:56)
    at D:\Projects\express-mongoose-jwt-es6-api\node_modules\mongodb\lib\bulk\unordered.js:465:9
    at handleCallback (D:\Projects\express-mongoose-jwt-es6-api\node_modules\mongodb\lib\utils.js:120:56)
    at resultHandler (D:\Projects\express-mongoose-jwt-es6-api\node_modules\mongodb\lib\bulk\unordered.js:413:5)
    at D:\Projects\express-mongoose-jwt-es6-api\node_modules\mongodb-core\lib\connection\pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by sergeybobryk** [comment]
Done
